---
version: '3'
services:
  node:
    image: cdd-aix/node:${node_tag}
    build:
      context: node
  node-build:
    image: cdd-aix/node-build:${node_tag}
    build:
      context: node
      dockerfile: Dockerfile-build
      args:
        NODE_TAG: ${node_tag}
  node-build2017:
    image: cdd-aix/node-build:${node_tag}-vs2017
    build:
      context: node
      dockerfile: Dockerfile-build2017
      args:
        NODE_TAG: ${node_tag}
  # node-bug:
  #   image: cdd-aix/node-bug:${node_tag}
  #   build:
  #     context: node
  #     dockerfile: Dockerfile-node-gyp-bug
  node-jnlp:
    image: cdd-aix/node-jnlp:${node_tag}
    build:
      context: node
      dockerfile: Dockerfile-jnlp
      args:
        BUILD_TAG: ${node_tag}
